//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEGIS_ADDSOURCE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\TEMP\\AEGIS\\SUB\\PRNFILE\\compiledprn.xls")]
        public string PRN {
            get {
                return ((string)(this["PRN"]));
            }
            set {
                this["PRN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\TEMP\\AEGIS\\tmtd.xml")]
        public string OFFICIAL_XML {
            get {
                return ((string)(this["OFFICIAL_XML"]));
            }
            set {
                this["OFFICIAL_XML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\TEMP\\AEGIS\\OUTPUT")]
        public string OUT_PATH {
            get {
                return ((string)(this["OUT_PATH"]));
            }
            set {
                this["OUT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\TEMP\\AEGIS\\SUB\\XML")]
        public string SUB_PATH {
            get {
                return ((string)(this["SUB_PATH"]));
            }
            set {
                this["SUB_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program_Codes\\AEGIS_ADDSOURCE\\AEGIS_ADDSOURCE\\bin\\Debug\\markers.txt")]
        public string MARKERS {
            get {
                return ((string)(this["MARKERS"]));
            }
            set {
                this["MARKERS"] = value;
            }
        }
    }
}
